# permissions for end users to edit certificaterequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificaterequest-editor-role
rules:
- apiGroups:
  - certman.managed.openshift.io
  resources:
  - certificaterequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certman.managed.openshift.io
  resources:
  - certificaterequests/status
  verbs:
  - get
