# permissions for end users to view certificaterequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificaterequest-viewer-role
rules:
- apiGroups:
  - certman.managed.openshift.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certman.managed.openshift.io
  resources:
  - certificaterequests/status
  verbs:
  - get
